In [1]:
import tensorflow as  tf 

In [2]:
c1 = tf.constant([10,20,30,40])

In [3]:
c1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 20, 30, 40])>

In [4]:
tf.constant(100)

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [5]:
tf.constant(10.25)

<tf.Tensor: shape=(), dtype=float32, numpy=10.25>

In [6]:
tf.constant("Welcome to DeepLearning")

<tf.Tensor: shape=(), dtype=string, numpy=b'Welcome to DeepLearning'>

In [7]:
tf.constant(10+2j)

<tf.Tensor: shape=(), dtype=complex128, numpy=(10+2j)>

In [8]:
a =100
b= 200
c= 300
d= 400

tf.constant([a,b,c])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([100, 200, 300])>

In [9]:
c2 = tf.constant([a,b,c,d])

In [10]:
c2

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([100, 200, 300, 400])>

In [11]:
c2.shape

TensorShape([4])

In [12]:
c2.ndim

1

In [13]:
c2.dtype

tf.int32

In [14]:
c3 =tf.constant([a,b,c,d], shape=[2,2])

In [15]:
c3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [300, 400]])>

In [16]:
c4 =tf.constant([a,b,c,d], shape=[2,2],dtype = tf.float32)

In [17]:
c4

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[100., 200.],
       [300., 400.]], dtype=float32)>

In [18]:
c5 = tf.constant([10,20,30,40,50,60],shape = (2,3), dtype = tf.float16)

In [19]:
c5

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float16)>

In [20]:
print(c5)

tf.Tensor(
[[10. 20. 30.]
 [40. 50. 60.]], shape=(2, 3), dtype=float16)


In [21]:
tf.print(c5)

[[10 20 30]
 [40 50 60]]


In [22]:
import numpy as np 
import pandas as pd 

In [23]:
c5.dtype

tf.float16

In [24]:
type(c5)

tensorflow.python.framework.ops.EagerTensor

In [25]:
ary1 = np.random.randint(10,30,(5))

In [26]:
ary1

array([21, 21, 16, 15, 16])

In [27]:
tf.constant(ary1)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([21, 21, 16, 15, 16])>

In [28]:
tf.print(tf.constant(ary1))

[21 21 16 15 16]


In [29]:
ary2 = np.random.randint(10,50,(4,5))

In [30]:
ary2

array([[45, 31, 13, 21, 47],
       [48, 20, 24, 26, 11],
       [45, 38, 38, 34, 24],
       [19, 31, 14, 33, 14]])

In [31]:
c6 = tf.constant(ary2)

In [32]:
c6

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[45, 31, 13, 21, 47],
       [48, 20, 24, 26, 11],
       [45, 38, 38, 34, 24],
       [19, 31, 14, 33, 14]])>

In [33]:
c6

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[45, 31, 13, 21, 47],
       [48, 20, 24, 26, 11],
       [45, 38, 38, 34, 24],
       [19, 31, 14, 33, 14]])>

In [34]:
tf.print(c6)

[[45 31 13 21 47]
 [48 20 24 26 11]
 [45 38 38 34 24]
 [19 31 14 33 14]]


In [35]:
df1  = pd.DataFrame(ary2)

In [36]:
df1

0   1   2   3   4
0  45  31  13  21  47
1  48  20  24  26  11
2  45  38  38  34  24
3  19  31  14  33  14

In [37]:
c7 = tf.constant(df1)

In [38]:
c7

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[45, 31, 13, 21, 47],
       [48, 20, 24, 26, 11],
       [45, 38, 38, 34, 24],
       [19, 31, 14, 33, 14]])>

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
z1 = tf.zeros(shape=(4,5))

In [42]:
z1

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [43]:
o1 = tf.ones(shape = (4,4))

In [44]:
o1

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [45]:
tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [46]:
tfc1 = tf.constant(np.arange(1,6))

In [47]:
tfc1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [48]:
tfc1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [49]:
tfc2 = tf.constant(np.arange(11,16))

In [50]:
tfc2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([11, 12, 13, 14, 15])>

In [51]:
tfc1 +  tfc2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([12, 14, 16, 18, 20])>

In [52]:
tfc1 * tfc2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([11, 24, 39, 56, 75])>

In [53]:
tfs1 = tf.constant("I Like ")

In [54]:
tfs2 = tf.constant(" TensorFlow ")

In [55]:
tfs1

<tf.Tensor: shape=(), dtype=string, numpy=b'I Like '>

In [56]:
tfs2

<tf.Tensor: shape=(), dtype=string, numpy=b' TensorFlow '>

In [57]:
tfs1 + tfs2

<tf.Tensor: shape=(), dtype=string, numpy=b'I Like  TensorFlow '>

In [58]:
tf.print(tfs1 + tfs2)

I Like  TensorFlow 


In [59]:
tfc1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [60]:
tfc2

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([11, 12, 13, 14, 15])>

In [61]:
tf.concat([tfc1, tfc2], axis= 0)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15])>

In [62]:
tf1 = tf.constant(np.random.randint(1,5,(2,2)))

In [63]:
tf2 = tf.constant(np.random.randint(1,5,(2,2)))

In [64]:
tf1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [4, 2]])>

In [65]:
tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [3, 3]])>

In [66]:
tf.concat([tf1, tf2], axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 1],
       [4, 2],
       [2, 1],
       [3, 3]])>

In [67]:
tf3 = tf.concat([tf1, tf2], axis=1)

In [68]:
tf3

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 1, 2, 1],
       [4, 2, 3, 3]])>

In [69]:
tf.print(tf3)

[[1 1 2 1]
 [4 2 3 3]]


In [70]:
tf3.shape

TensorShape([2, 4])

In [71]:
tf.reshape(tf3, shape=(4,2))

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 1],
       [2, 1],
       [4, 2],
       [3, 3]])>

In [72]:
tf4 = tf.constant([10,20,30,40,50,60], shape=(3,2), dtype = tf.float32)

In [73]:
tf4

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10., 20.],
       [30., 40.],
       [50., 60.]], dtype=float32)>

In [74]:
tf.cast(tf4, tf.int32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]])>

In [75]:
tf4.shape

TensorShape([3, 2])

In [76]:
tf.transpose(tf4).shape

TensorShape([2, 3])

In [77]:
tfc1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [78]:
tf.argmax(tfc1)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [79]:
tfc3 = np.random.randint(10,20,(6))

In [80]:
tfc3

array([19, 19, 14, 19, 17, 14])

In [81]:
tf.argmax(tfc3)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [82]:
tf.argmin(tfc3)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [83]:
tf1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [4, 2]])>

In [84]:
tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [3, 3]])>

In [85]:
tf1 + tf2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [7, 5]])>

In [86]:
tf.add(tf1, tf2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [7, 5]])>

In [87]:
tf1 -  tf2 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1,  0],
       [ 1, -1]])>

In [88]:
tf.subtract(tf1, tf2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1,  0],
       [ 1, -1]])>

In [89]:
display(tf1,tf2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [4, 2]])>

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [3, 3]])>

tf1 * tf2

In [90]:
tf.matmul(tf1,tf2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  4],
       [14, 10]])>

In [91]:
tf.multiply(tf1, tf2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  1],
       [12,  6]])>